# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 3pio < Formula
  desc "Context-optimized test runner adapter for AI agents"
  homepage "https://github.com/zk/3pio"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zk/3pio/releases/download/v0.1.0/3pio-darwin-amd64.tar.gz"
      sha256 "78426fbe4d7b5f02790d3fbad024f8e870d2ddac3b204005553d47f89efcdcf0"

      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zk/3pio/releases/download/v0.1.0/3pio-darwin-arm64.tar.gz"
      sha256 "794345aa1dc71f492b86bfe7fdfbb2cbc70635c3bd668c176c3a1ff48ab7dd1c"

      def install
        bin.install "3pio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.1.0/3pio-linux-amd64.tar.gz"
      sha256 "088e920dceabc438dabcaaa25611db84a8cf7b839e60003018a671ce85aaa223"
      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.1.0/3pio-linux-arm64.tar.gz"
      sha256 "7850309283acb15c3eefeb6bb6a3cef7c8886c04a1ea412d655e3b762c88e3f7"
      def install
        bin.install "3pio"
      end
    end
  end

  def caveats
    <<~EOS
      3pio translates test runs into a format optimized for AI agents.

      Usage examples:
        3pio npm test                    # Run npm test script
        3pio npm test -- tests/unit      # Pass arguments to npm test
        3pio npx jest                    # Run Jest directly
        3pio npx vitest run              # Run Vitest
        3pio pytest                      # Run pytest

      Reports are written to .3pio/runs/[timestamp]-[memorable-name]/

      For more information: https://github.com/zk/3pio
    EOS
  end

  test do
    system "#{bin}/3pio --help"
    system "#{bin}/3pio --version"
  end
end
