# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 3pio < Formula
  desc "Context-optimized test runner adapter for AI agents"
  homepage "https://github.com/zk/3pio"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zk/3pio/releases/download/v0.6.0/3pio-darwin-amd64.tar.gz"
      sha256 "b320c3eeadd3b25faaa70f56b139701eca5f45474f940af49f483dce4bae7a61"

      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zk/3pio/releases/download/v0.6.0/3pio-darwin-arm64.tar.gz"
      sha256 "3b2dd140642b421be347b812e2bf8a431681c27eb83c2f26d87583bf8d9d7887"

      def install
        bin.install "3pio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.6.0/3pio-linux-amd64.tar.gz"
      sha256 "884a296074969c36f3b8056d50950f20de8a3185f56fc13226c236f58a8675d1"
      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.6.0/3pio-linux-arm64.tar.gz"
      sha256 "9205400b161245dc216689cd62ecc6241d9ac628beee422bfb331ccf2cc74aa4"
      def install
        bin.install "3pio"
      end
    end
  end

  def caveats
    <<~EOS
      3pio translates test runs into a format optimized for AI agents.

      Usage examples:
        3pio npm test                    # Run npm test script
        3pio npm test -- tests/unit      # Pass arguments to npm test
        3pio npx jest                    # Run Jest directly
        3pio npx vitest run              # Run Vitest
        3pio pytest                      # Run pytest

      Reports are written to .3pio/runs/[timestamp]-[memorable-name]/

      For more information: https://github.com/zk/3pio
    EOS
  end

  test do
    system "#{bin}/3pio --help"
    system "#{bin}/3pio --version"
  end
end
