# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class 3pio < Formula
  desc "Context-optimized test runner adapter for AI agents"
  homepage "https://github.com/zk/3pio"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zk/3pio/releases/download/v0.7.2/3pio-darwin-amd64.tar.gz"
      sha256 "cc02d2f0bfe3dab6a86d7f21299f150d17223e7da567e4b8cbb7497f61cf92f6"

      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zk/3pio/releases/download/v0.7.2/3pio-darwin-arm64.tar.gz"
      sha256 "8ed988e23e67696aa813e4f4f327fe7b1f91231031970a052f0b3157ed3c78fc"

      def install
        bin.install "3pio"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.7.2/3pio-linux-amd64.tar.gz"
      sha256 "1a5f59eb5bce8b52bbd9f2d04fcde80d4d4223bc6fbf2e55459ba7b518debc23"
      def install
        bin.install "3pio"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zk/3pio/releases/download/v0.7.2/3pio-linux-arm64.tar.gz"
      sha256 "04700cc7018dc42ba748d77e7eda5125eedcb41ed7ec01a0049baac9ef2d702b"
      def install
        bin.install "3pio"
      end
    end
  end

  def caveats
    <<~EOS
      3pio translates test runs into a format optimized for AI agents.

      Usage examples:
        3pio npm test                    # Run npm test script
        3pio npm test -- tests/unit      # Pass arguments to npm test
        3pio npx jest                    # Run Jest directly
        3pio npx vitest run              # Run Vitest
        3pio pytest                      # Run pytest

      Reports are written to .3pio/runs/[timestamp]-[memorable-name]/

      For more information: https://github.com/zk/3pio
    EOS
  end

  test do
    system "#{bin}/3pio --help"
    system "#{bin}/3pio --version"
  end
end
